CREATE TABLE catalogo (
    id BINARY(16) PRIMARY KEY,
    tenant_id BINARY(16) NOT NULL,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;